name = "INotify"
uuid = "9e73f634-81c6-42cf-8211-fb9f7b28b16d"
authors = ["David MacMahon <davidm@astro.berkeley.edu> and contributors"]
version = "0.1.1"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
